[workspace]
resolver = "2"
members = [
    "chapter02/hello_world/hello_world_guest",
    "chapter03/smartcms_test_host",
    "chapter04/hello_world_wasi/hello_world_wasi_guest/hello_world_wasi_host",
    "chapter04/wasi02/hello_world_wasi02",
]
